name: Sandbox. CI/CD with Blue/Green Deployment
run-name: Deploy ${{ inputs.git-ref }} to ${{ inputs.deployment-env }} by ${{ github.actor }} 🚀
on:
  workflow_dispatch:
    inputs:
      software-setup:
        description: 'Setup/configure required software on EC2 instances (Optional)'
        default: false
        type: boolean
      deployment-env:
        description: 'Deployment environment'
        required: true
        default: 'blue'
        type: choice
        options:
          - blue
          - green
      git-ref:
        description: 'Git Reference (Optional. branch/commit hash)'
        required: false

concurrency:
  group: sandbox
  cancel-in-progress: false

env:
  AWS_DEFAULT_REGION: eu-west-2
  GIT_BRANCH: dev

jobs:
  confirmation:
    runs-on: ubuntu-latest
    steps:
      - name: Confirm manual workflow run
        id: confirm
        run: |
          read -p "Are you sure you want to run this workflow manually? (y/n): " confirm
          if [ "$confirm" != "y" ]; then
            echo "Workflow run cancelled."
            exit 1
          fi

  main:
    runs-on: ubuntu-latest
    needs: confirmation
    steps:
      - name: create file
        run: echo "${{ env.AWS_DEFAULT_REGION }}" > region.txt
