name: Sandbox. CI/CD with Blue/Green Deployment
run-name: Deploy ${{ inputs.git-ref }} to ${{ inputs.deployment-env }} by ${{ github.actor }} 🚀
on:
  workflow_dispatch:
    inputs:
      software-setup:
        description: 'Setup/configure required software on EC2 instances (Optional)'
        default: false
        type: boolean
      deployment-env:
        description: 'Deployment environment'
        required: true
        default: 'blue'
        type: choice
        options:
          - blue
          - green
      git-ref:
        description: 'Git Reference (Optional. branch/commit hash)'
        required: false

concurrency:
  group: sandbox
  cancel-in-progress: false

env:
  AWS_DEFAULT_REGION: eu-west-2
  GIT_BRANCH: main

jobs:
  confirmation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.GIT_BRANCH }}
        if: github.event.inputs.git-ref == ''

      - name: Get git message
        id: deploy-message
        run: |
          {
            echo 'commit_msg<<EOF'
            $(git log -1 --format=%B)
            echo EOF
          } >> "$GITHUB_OUTPUT"
          echo "commit_sha=$(git log -1 --format=%H)" >> "$GITHUB_OUTPUT"
          
      - name: Slack Notification
        run: |
          echo "${{ steps.deploy-message.outputs.commit_msg }}"
          echo "${{ steps.deploy-message.outputs.commit_sha }}"
